export const casesData = [
  {
    cover: '/image path/',
    title_ua: 'Юлія',
    title_en: 'Julia',
    title_de: 'Julia',
    title_ru: 'Юлия',
    description_ua: '24 роки',
    description_en: '24 years old',
    description_de: '24 Jahre alt',
    description_ru: '24 года',
    slug: '/case-template/',
  },
  {
    cover: '/image path/',
    title_ua: 'Юлія',
    title_en: 'Julia',
    title_de: 'Julia',
    title_ru: 'Юлия',
    description_ua: '24 роки',
    description_en: '24 years old',
    description_de: '24 Jahre alt',
    description_ru: '24 года',
    slug: '/case-template/',
  },
  {
    cover: '/image path/',
    title_ua: 'Юлія',
    title_en: 'Julia',
    title_de: 'Julia',
    title_ru: 'Юлия',
    description_ua: '24 роки',
    description_en: '24 years old',
    description_de: '24 Jahre alt',
    description_ru: '24 года',
    slug: '/case-template/',
  },
  {
    cover: '/image path/',
    title_ua: 'Юлія',
    title_en: 'Julia',
    title_de: 'Julia',
    title_ru: 'Юлия',
    description_ua: '24 роки',
    description_en: '24 years old',
    description_de: '24 Jahre alt',
    description_ru: '24 года',
    slug: '/case-template/',
  },
  {
    cover: '/image path/',
    title_ua: 'Юлія',
    title_en: 'Julia',
    title_de: 'Julia',
    title_ru: 'Юлия',
    description_ua: '24 роки',
    description_en: '24 years old',
    description_de: '24 Jahre alt',
    description_ru: '24 года',
    slug: '/case-template/',
  },
  {
    cover: '/image path/',
    title_ua: 'Юлія',
    title_en: 'Julia',
    title_de: 'Julia',
    title_ru: 'Юлия',
    description_ua: '24 роки',
    description_en: '24 years old',
    description_de: '24 Jahre alt',
    description_ru: '24 года',
    slug: '/case-template/',
  },
];
