export const servicesData = {
  title_ua: 'Послуги',
  title_en: 'Services',
  title_de: 'Dienstleistungen',
  title_ru: 'Услуги',
  slug: '/services/',
  items: [
    {
      slug: '/services-inner/',
      image: '../../../../../svg/mam.svg',
      title_ua: 'Мамопластика',
      title_en: 'Mammoplasty',
      title_de: 'Mammoplastik',
      title_ru: 'Маммопластика',
    },
    {
      slug: '/rservices-inner/',
      image: '../../../../../svg/rin.svg',
      title_ua: 'Ринопластика',
      title_en: 'Rhinoplasty',
      title_de: 'Nasenkorrektur',
      title_ru: 'Ринопластика',
    },
    {
      slug: '/services-inner/',
      image: '../../../../../svg/lip.svg',
      title_ua: 'Ліпосакція',
      title_en: 'Liposuction',
      title_de: 'Fettabsaugung',
      title_ru: 'Липосакция',
    },
    {
      slug: '/services-inner/',
      image: '../../../../../svg/fac.svg',
      title_ua: 'Хірургія обличчя',
      title_en: 'Facial surgery',
      title_de: 'Gesichtschirurgie',
      title_ru: 'Хирургия лица',
      category: [
        {
          slug: '/services-inner/',
          title_ua: 'Комки Біша',
          title_en: 'Lumps of Bish',
          title_de: 'Klumpen von Bish',
          title_ru: 'Комки Биша',
        },
        {
          slug: '/services-inner/',
          title_ua: 'Верхня Блефаропластика',
          title_en: 'Upper Blepharoplasty',
          title_de: 'Obere Blepharoplastik',
          title_ru: 'Верхняя Блефаропластика',
        },
        {
          slug: '/services-inner/',
          title_ua: 'Нижня Блефаропластика',
          title_en: 'Lower Blepharoplasty',
          title_de: 'Untere Blepharoplastik',
          title_ru: 'Нижняя Блефаропластика',
        },
        {
          slug: '/services-inner/',
          title_ua: 'Отопластика',
          title_en: 'Otoplasty',
          title_de: 'Otoplastik',
          title_ru: 'Отопластика',
        },
        {
          slug: '/services-inner/',
          title_ua: 'Булхорн',
          title_en: 'Bulhorn',
          title_de: 'Bulhorn',
          title_ru: 'Булхорн',
        },
      ],
    },
  ],
};
