export const workData = {
  title_ua: 'Роботи',
  title_en: 'Works',
  title_de: 'Arbeit',
  title_ru: 'Работы',
  items: [
    {
      slug: '/work-inner/',
      image: '/image path/',
      title_ua: 'Ринопластика',
      title_en: 'Rhinoplasty',
      title_de: 'Nasenkorrektur',
      title_ru: 'Ринопластика',
    },
    {
      slug: '/work-inner/',
      image: '/image path/',
      title_ua: 'Збільшення грудей',
      title_en: 'Breast augmentation',
      title_de: 'Brustvergrößerung',
      title_ru: 'Увеличение груди',
    },
    {
      slug: '/work-inner/',
      image: '/image path/',
      title_ua: 'Блефаропластика',
      title_en: 'Blepharoplasty',
      title_de: 'Blepharoplastik',
      title_ru: 'Блефаропластика',
    },
    {
      slug: '/work-inner/',
      image: '/image path/',
      title_ua: 'Ліпосакція',
      title_en: 'Liposuction',
      title_de: 'Fettabsaugung',
      title_ru: 'Липосакция',
    },
  ],
};
